# Generated by Django 3.2.7 on 2021-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineids',
            name='machine_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
