from django.urls import path
from . import PatientReportViews, HomeView, RequisitionView, AssayView, UserView, ResultEntryView, ReportView, ProductView

urlpatterns = [
    path('', HomeView.home, name='home'),
    path('assay/', AssayView.assay, name='assay'),
    path('requisition_form/', RequisitionView.requisition_form,name='requisition_form'),
    path('search_req/', RequisitionView.search_req, name='search_req'),
    path('open_report/<anpac_id>', RequisitionView.open_report, name='open_report'),
    path('succcess/', PatientReportViews.success, name='success'),
    path('login', UserView.user_login, name='user_login'),
    path('import_requisitions/', RequisitionView.import_requisitions, name='import_requisitions'),
    path('logout/', UserView.logout_user, name='logout_user'),
    path('register/', UserView.register_user, name='register'),
    path('edit_profile/', UserView.edit_profile,name='edit_profile'),
    path('change_password/', UserView.change_password, name='change_password'),
    path('result_entry/', ResultEntryView.result_entry, name='result_entry'),
    path('create_report/', ReportView.create_report, name='create_report'),
    path('op_machine_assignment/', AssayView.op_machine_assignment, name='op_machine_assignment'),
    path('approval_sign_off/', PatientReportViews.approval_sign_off, name='approval_sign_off'),
    path('final_reports/', PatientReportViews.final_reports, name='final_reports'),
    path('patient_view_results/<anpac_id>', ReportView.patient_view_results, name='patient_view_results'),
    path('patient_cobas_results/<anpac_id>', PatientReportViews.patient_cobas_results, name='patient_cobas_results'),
    path('patient_cda_results/<anpac_id>', PatientReportViews.patient_cda_results, name='patient_cda_results'),
    path('approve_report_cda/<anpac_id>', PatientReportViews.approve_report_cda, name='approve_report_cda'),
    path('approve_report_cobas/<anpac_id>', PatientReportViews.approve_report_cobas, name='approve_report_cobas'),
    path('download_req_excel/', RequisitionView.download_req_excel, name='download_req_excel'),
    path('final_cobas_results/<anpac_id>', PatientReportViews.final_cobas_results, name='final_cobas_results'),
    path('approved_cda_results/<anpac_id>', PatientReportViews.approved_cda_results, name='approved_cda_results'),
    path('email_final_report/<anpac_id>', PatientReportViews.email_final_report, name='email_final_report'),
    path('archive/', RequisitionView.archive, name='archive'),
    path('view_requisition_readonly/<anpac_id>', RequisitionView.view_requisition_readonly, name='view_requisition_readonly'),
    path('devices/', ProductView.devices, name='devices'),
    path('ResetBatchAmount/<machine_identifier>', ProductView.ResetBatchAmount, name='ResetBatchAmount'),
    ]